# Let's not use the "netlify" domain
#[[redirects]]
#  from = "https://aptos-test-page.netlify.app"
#  to = "https://test-page.gnazar.io"
#  status = 301
#  force = true

# Ensure that SPA works correctly
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
